apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/adminer
  - adminer-secrets.yaml
  - adminer-config-cm.yaml
  - adminer-basic-auth.yaml
patchesStrategicMerge:
  - adminer-values.yaml
