---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: rancher
  namespace: cattle-system
spec:
  values:
    privateCA: true
    hostname: rancher.homelab.local
    bootstrapPassword: change123
    ingress:
      tls:
        source: secrets
